# nbpb_config.yaml
# NBPB Configuration - NeuroBulla Pipeline Bodies
project_name: "Pipeline"
version: "draft : 0.1.0"

# NBPB organ configuration
organs:

  # Watcher - Monitoring data transformations
  watcher:
    enabled: true
    sampling_rate: 0.2             # frazioni di batch da monitorare
    shift_threshold: 3.5          # valore di shift oltre cui scatta l'alert
    drift_threshold: 0.1
    schema_validation: true
    memory_threshold_mb: 1000

  # ImmunoGuard - Leakage detection
  immuno_guard:
    enabled: true
    target_correlation_threshold: 0.05
    target_correlation_critical_threshold: 0.8
    target_correlation_warning_threshold: 0.6
    multicollinearity_threshold: 0.95
    mutual_info_threshold: 0.3
    temporal_check: true

  # Loss-Smith - Auto-generation of loss functions (SCAFFOLD)
  loss_smith:
    enabled: true
    loss_config_path: "nbpb/loss_configs/default.loss.json"
    positive_class_weight: 0.8    # pesi personalizzati per la loss
    negative_class_weight: 0.2

  # Reverse-Engine - Ideal datasets from target output (SCAFFOLD)
  reverse_engine:
    enabled: true
    output_data_path: "nbpb/generated/ideal_dataset.csv"

  # Hormone-Ctrl - Parameter self-regulation (SCAFFOLD)
  hormone_ctrl:
    enabled: true
    lr_min: 1e-6
    lr_max: 5e-3
    freeze_after_epoch: 5

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  file: "nbpb.log"
  console_output: true